import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from 'next/font/google';
import "./globals.css";
import { FaLongArrowAltUp } from "react-icons/fa";

// import Navbar from "./common/navbar/Navbar";


const outfit = Outfit({ subsets: ['latin'], weight: ["300", "400", "600", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ahmad Raza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.className} antialiased`}
      >

        {children}

      </body>
    </html>
  );
}
